GET http://localhost:3000/

###
// Register
POST http://localhost:3000/register
Content-Type: application/json

{
  "registerRequest": {
    "credentials": "dXNlcjpwYXNz",
    "loginNow": true
  }
}

###
// Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "loginRequest": {
    "credentials": "dXNlcjpwYXNz"
  }
}